# Generated by Django 5.2.7 on 2025-10-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
