# Generated by Django 5.2.7 on 2025-10-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
