# Generated by Django 5.2.7 on 2025-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0003_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('reception', 'Reception'), ('mehendi', 'Mehendi'), ('haldi', 'Haldi'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
