# Generated by Django 5.2.7 on 2025-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0005_contactsettings_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main hero headline', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('cta_text', models.CharField(default='Plan Your Dream Wedding', max_length=100)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome class, e.g., fa-solid fa-heart', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
            },
        ),
    ]
