# Generated by Django 5.2.7 on 2025-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0006_herosection_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this item in homepage preview'),
        ),
    ]
