# Generated by Django 5.2.7 on 2025-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0007_alter_gallery_options_gallery_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='preview/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPreviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('video', models.FileField(upload_to='preview/videos/')),
                ('thumbnail', models.ImageField(upload_to='preview/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='featured',
        ),
    ]
