# Generated by Django 5.2.7 on 2025-11-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0008_gallerypreviewimage_gallerypreviewvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypreviewvideo',
            name='thumbnail',
        ),
    ]
