# Generated by Django 5.2.7 on 2025-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0009_remove_gallerypreviewvideo_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypreviewimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='gallerypreviewvideo',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='gallerypreviewimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gallerypreviewvideo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
