# Generated by Django 5.2.7 on 2025-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0010_rename_uploaded_at_gallerypreviewimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypreviewimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Gallery Preview Image', 'verbose_name_plural': 'Gallery Preview Images'},
        ),
        migrations.AlterModelOptions(
            name='gallerypreviewvideo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Gallery Preview Video', 'verbose_name_plural': 'Gallery Preview Videos'},
        ),
        migrations.RenameField(
            model_name='gallerypreviewimage',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='gallerypreviewvideo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='gallerypreviewimage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gallerypreviewvideo',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
