# Generated by Django 5.2.7 on 2025-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0011_alter_gallerypreviewimage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPreviewVideo',
        ),
        migrations.AlterModelOptions(
            name='gallerypreviewimage',
            options={},
        ),
        migrations.RenameField(
            model_name='gallerypreviewimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='gallerypreviewimage',
            name='category',
            field=models.CharField(choices=[('wedding', 'Weddings'), ('corporate', 'Corporate'), ('party', 'Parties'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallerypreviewimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
