# Generated by Django 5.2.7 on 2025-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0012_delete_gallerypreviewvideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='gallery/preview/')),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('parties', 'Parties'), ('birthdays', 'Birthdays')], default='wedding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryPreviewImage',
        ),
    ]
