# Generated by Django 5.2.7 on 2025-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0013_gallerypreview_delete_gallerypreviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypreview',
            name='image',
            field=models.ImageField(upload_to='gallery_preview/'),
        ),
        migrations.AlterField(
            model_name='gallerypreview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
