# Generated by Django 5.2.7 on 2025-11-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0014_alter_gallerypreview_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='gallerypreview',
            name='image',
            field=models.ImageField(upload_to='gallery/preview/'),
        ),
        migrations.AlterField(
            model_name='gallerypreview',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
