# Generated by Django 5.2.7 on 2025-11-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0015_alter_gallerypreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='gallerypreview',
            name='category',
        ),
    ]
