# Generated by Django 5.2.7 on 2025-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0016_alter_gallerypreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPreviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='gallery/preview/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryPreview',
        ),
    ]
