# Generated by Django 5.2.7 on 2025-11-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0017_gallerypreviewitem_delete_gallerypreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypreviewitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Gallery Preview Item', 'verbose_name_plural': 'Gallery Preview Items'},
        ),
        migrations.RemoveField(
            model_name='gallerypreviewitem',
            name='position',
        ),
        migrations.AddField(
            model_name='gallerypreviewitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers shown first'),
        ),
        migrations.AlterField(
            model_name='gallerypreviewitem',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
