# Generated by Django 5.2.7 on 2025-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0019_gallerypreview_delete_gallerypreviewitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPreviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='gallery/preview/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Preview Item',
                'verbose_name_plural': 'Gallery Preview Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryPreview',
        ),
    ]
