# Generated by Django 5.2.7 on 2025-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0020_gallerypreviewitem_delete_gallerypreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPreviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Moments We’ve Crafted', max_length=150)),
                ('subheading', models.CharField(default='Click any image to expand — it grows in place and other cards gently shrink.', max_length=255)),
            ],
            options={
                'verbose_name': 'Gallery Preview Text',
                'verbose_name_plural': 'Gallery Preview Text',
            },
        ),
    ]
