# Generated by Django 5.2.7 on 2025-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0021_gallerypreviewsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
