# Generated by Django 5.2.7 on 2025-12-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0023_alter_about_image_alter_contactsettings_map_embed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fa-solid fa-heart', help_text='FontAwesome class, e.g. fa-solid fa-ring', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='section',
            field=models.CharField(default='General Services', help_text='Main service category, e.g. Wedding Stationery & Design', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
