# Generated by Django 5.2.7 on 2025-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0024_alter_service_options_remove_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order'],
            },
        ),
    ]
