# Generated by Django 5.2.7 on 2025-12-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0025_gallerycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wedtree.gallerycategory'),
        ),
    ]
