# Generated by Django 5.2.7 on 2025-12-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0026_gallery_category_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='category_new',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wedtree.gallerycategory'),
        ),
    ]
