# Generated by Django 5.2.7 on 2025-12-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0027_alter_gallery_options_remove_gallery_category_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='wedtree.gallerycategory'),
        ),
    ]
