# Generated by Django 5.2.7 on 2025-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0028_alter_gallery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video',
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, help_text='Upload video to Cloudinary and paste the URL here', null=True),
        ),
    ]
