# Generated by Django 5.2.7 on 2025-12-27 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedtree', '0029_remove_gallery_video_gallery_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
